version: "3.7"
services:
  db:
    networks: 
      - project
  server:
    build: .
    container_name: server
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: bash -c "npm run migrate && npm run seed:run && npm run start"
    networks: 
      - project
    restart: always
networks: 
  project:


